# TfmEngine — JSI host module (iOS).
#
# Installed via CocoaPods:  pod 'TfmEngine', :path => '../native'
# (plugins/withTfmEngine.js injects that line into ios/Podfile during prebuild).
#
# Compiles the shared transformer engine (cpp/src/*.cpp) plus the JSI glue
# (native/cpp/TfmEngine.cpp) into the app. The TurboModule is registered at
# runtime from the app delegate — see native/README.md "iOS" for the exact
# snippet. We deliberately do NOT touch the filesystem: weights are embedded in
# native/include/tfm_model_data.h (generated by scripts/embed_weights.py).

require "json"

Pod::Spec.new do |s|
  s.name         = "TfmEngine"
  s.version      = "0.1.0"
  s.summary      = "JSI host module wrapping the TFM transformer engine"
  s.homepage     = "https://github.com/neoncube/ttt"
  s.license      = { :type => "MIT" }
  s.author       = { "NeonCube" => "dev@neoncube.example" }
  s.platforms    = { :ios => "16.4" }
  s.source       = { :path => File.dirname(__FILE__) }

  # --- Sources ---------------------------------------------------------------
  # JSI glue + embedded-weights loader (this module) and the shared engine
  # sources (from <repo>/cpp, referenced read-only via relative paths).
  s.source_files = [
    "cpp/*.cpp",
    "cpp/*.h",
    "include/*.hpp",
    "../../cpp/src/*.cpp",
    "../../cpp/include/tfm/*.hpp",
  ]
  s.header_mappings_dir = "../../cpp/include"  # keep `tfm/model.hpp` importable

  # --- Dependencies ----------------------------------------------------------
  s.dependency "React-Core"
  s.dependency "ReactCommon"
  s.dependency "React-jsi"
  s.dependency "React-callinvoker"

  # --- Compile settings ------------------------------------------------------
  # RN's bridging headers (pulled in by TurboModule.h) require C++20.
  s.pod_target_xcconfig = {
    "HEADER_SEARCH_PATHS" =>
      '"$(PODS_ROOT)/Headers/Public" ' \
      '"$(PODS_ROOT)/Headers/Public/ReactCommon" ' \
      '"$(PODS_ROOT)/Headers/Public/React-Core" ' \
      '"$(PODS_ROOT)/Headers/Public/jsi" ' \
      '"$(PODS_ROOT)/Headers/Private/React-Core" ' \
      '"$(PODS_TARGET_SRCROOT)/.." ' \
      '"$(PODS_TARGET_SRCROOT)/../../cpp/include" ' \
      '"$(PODS_TARGET_SRCROOT)/include" ' \
      '"$(PODS_TARGET_SRCROOT)/cpp" ' \
      '"$(PODS_TARGET_SRCROOT)/../node_modules/react-native/ReactCommon"',
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++20",
    "CLANG_CXX_LIBRARY" => "libc++",
    "USE_HEADERMAP" => "NO",
    "GCC_PREPROCESSOR_DEFINITIONS" => '$(inherited)',
  }
end