/**
 * Generates `src/three/models.ts` from the Blender-authored GLB files in
 * `assets/models/`.
 *
 * Why: on Android the three.js FileLoader cannot fetch `file://` asset URIs and
 * we don't want a native file-system dependency. Baking the vertex/index data
 * into a TypeScript module means the Blender geometry ships through Metro like
 * any other JS — zero runtime parsing, zero new native deps, and it works
 * identically in Expo Go / dev / release builds.
 *
 * Run after re-exporting models from Blender:
 *   node scripts/gen_models.mjs
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const MODELS_DIR = path.join(__dirname, '..', 'assets', 'models')
const OUT_FILE = path.join(__dirname, '..', 'src', 'three', 'models.ts')

const MODELS = ['slot', 'mark_x', 'mark_o', 'spark', 'podium', 'trophy']

function round(v, p = 5) {
  const f = Math.round(v * 10 ** p) / 10 ** p
  return Object.is(f, -0) ? 0 : f
}

const loader = new GLTFLoader()

const out = []

for (const name of MODELS) {
  const file = path.join(MODELS_DIR, `${name}.glb`)
  if (!fs.existsSync(file)) {
    console.warn(`skipping ${name}: ${file} not found`)
    continue
  }
  const buf = fs.readFileSync(file)
  const arrayBuf = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength)
  const gltf = await loader.parseAsync(arrayBuf, '')

  const positions = []
  const normals = []
  const indices = []
  let min = [Infinity, Infinity, Infinity]
  let max = [-Infinity, -Infinity, -Infinity]

  gltf.scene.traverse((obj) => {
    if (!obj.isMesh) return
    const geo = obj.geometry
    const pos = geo.attributes.position
    const nrm = geo.attributes.normal
    const base = positions.length / 3
    for (let i = 0; i < pos.count; i++) {
      const x = pos.getX(i)
      const y = pos.getY(i)
      const z = pos.getZ(i)
      positions.push(round(x), round(y), round(z))
      min[0] = Math.min(min[0], x)
      min[1] = Math.min(min[1], y)
      min[2] = Math.min(min[2], z)
      max[0] = Math.max(max[0], x)
      max[1] = Math.max(max[1], y)
      max[2] = Math.max(max[2], z)
    }
    if (nrm) {
      for (let i = 0; i < nrm.count; i++) {
        normals.push(round(nrm.getX(i)), round(nrm.getY(i)), round(nrm.getZ(i)))
      }
    }
    const idx = geo.index
    if (idx) {
      for (let i = 0; i < idx.count; i++) indices.push(idx.getX(i) + base)
    } else {
      for (let i = 0; i < pos.count; i++) indices.push(base + i)
    }
  })

  const size = [round(max[0] - min[0]), round(max[1] - min[1]), round(max[2] - min[2])]
  const bounds = {
    min: [round(min[0]), round(min[1]), round(min[2])],
    max: [round(max[0]), round(max[1]), round(max[2])],
  }

  out.push(`  '${name}': {
    positions: [${positions.join(', ')}],
    normals: [${normals.join(', ')}],
    indices: [${indices.join(', ')}],
    bounds: { min: [${bounds.min.join(', ')}], max: [${bounds.max.join(', ')}] },
    size: [${size.join(', ')}],
  },`)
}

const ts = `/**
 * GENERATED by scripts/gen_models.mjs — do not edit by hand.
 * Blender-authored low-poly geometry baked from assets/models/*.glb.
 */

export interface ModelBounds {
  min: [number, number, number]
  max: [number, number, number]
}

export interface ModelData {
  positions: number[]
  normals: number[]
  indices: number[]
  bounds: ModelBounds
  /** full extent (max - min) along each axis */
  size: [number, number, number]
}

export const MODELS: Record<string, ModelData> = {
${out.join('\n')}
}

export type ModelName = keyof typeof MODELS
`

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })
fs.writeFileSync(OUT_FILE, ts)
console.log(`wrote ${OUT_FILE} (${(ts.length / 1024).toFixed(1)} KB)`)
