/**
 * THE AI PARITY GATE.
 *
 * Replays every fixture generated by the REAL Python backend
 * (mobile-rn/scripts/gen_parity_fixture.py, run with the C++ engine) through
 * the ported TS mover, using:
 *   - a mock engine that answers from the captured evalPosition table, and
 *   - a scripted RNG that pops the recorded random/choice draw sequence.
 *
 * The TS mover must choose exactly the move Python chose.
 *
 * Contract note: the mover passes board.cells RAW ({0,1,2}) to
 * engine.evalPosition and the engine normalizes to the side-to-move's tokens
 * internally — exactly like Python's CppModel.eval_position (and the TS
 * NativeEngine). The fixture captured the RAW cells input, so the mock looks
 * up by raw (cells, player, n).
 */

import { Board } from '../game/board'
import type { Cell } from '../game/types'
import type { Difficulty, EvalResult } from '../ai/types'
import { LookaheadMover } from '../ai/mover'
import { OpponentPredictor } from '../ai/predictor'
import { createMockEngine } from '../ai/engine'
import { scriptedRng } from './rng-helper'

// eslint-disable-next-line @typescript-eslint/no-require-imports
import parityFixture from './fixtures/parity.json'

interface CaptureEntry {
  cells: number[]
  player: number
  n: number
  value: number
  policy: number[]
}

interface ParityCase {
  size: number
  position: number[]
  ai: number
  difficulty: Difficulty
  capture: CaptureEntry[]
  rng: Array<[string, number, number?]>
  expectedMove: number
}

const cases: ParityCase[] = (parityFixture as unknown as { cases: ParityCase[] }).cases

function buildLookup(capture: CaptureEntry[]): Map<string, EvalResult> {
  const map = new Map<string, EvalResult>()
  for (const e of capture) {
    const key = JSON.stringify([e.cells, e.player, e.n])
    if (!map.has(key)) {
      map.set(key, { value: e.value, policy: e.policy })
    }
  }
  return map
}

describe('AI parity with the Python backend', () => {
  for (const c of cases) {
    it(`n=${c.size} ${c.difficulty} -> move ${c.expectedMove}`, () => {
      const lookup = buildLookup(c.capture)
      const engine = createMockEngine((cells, player, n) => {
        const key = JSON.stringify([cells, player, n])
        const res = lookup.get(key)
        if (!res) {
          throw new Error(`no captured evalPosition output for ${key}`)
        }
        return res
      })

      const board = new Board(c.size, c.position as Cell[])
      const pred = new OpponentPredictor(board, engine)
      const scripted = scriptedRng(
        c.rng.map((e) =>
          e[0] === 'random'
            ? { kind: 'random' as const, value: e[1] as number }
            : { kind: 'choice' as const, value: e[2] as number, len: e[1] as number },
        ),
      )
      const mover = new LookaheadMover(engine, board, pred, c.difficulty, scripted.rng)

      const move = mover.chooseMove(c.ai as Cell)
      expect(move).toBe(c.expectedMove)
      expect(scripted.remaining()).toBe(0)
    })
  }
})